[package]
name = "sorting_algorithm"
version = "0.1.0"
authors = ["Universemul <davidbarthelemy28@gmail.com>"]
description = "A simple rust program sorting array"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]